[package]
authors = ["Semen <solomennikov@phystech.edu>"]
edition = "2018"
name = "rust_threads"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
